{
    "name": "EL MOKRIF HR Extension",
    "summary": "Confidential HR workflows, appraisals, and contract expiry controls",
    "version": "17.0.1.0.0",
    "category": "Human Resources",
    "author": "EL MOKRIF",
    "license": "LGPL-3",
    "depends": [
        "hr",
        "hr_contract",
        "hr_holidays",
        "hr_recruitment",
        "mail",
    ],
    "data": [
        "security/hr_groups.xml",
        "security/ir.model.access.csv",
        "security/hr_rules.xml",
        "data/hr_activity_data.xml",
        "data/hr_cron.xml",
        "views/hr_contract_views.xml",
        "views/hr_leave_views.xml",
        "views/hr_appraisal_views.xml",
    ],
    "installable": True,
    "application": True,
}
