[options]
admin_passwd = uat-master-password
db_host = soloodoo-uat-db
db_port = 5432
db_user = odoo_uat
db_password = uat-db-password
addons_path = /mnt/extra-addons,/opt/elmokrif-addons
without_demo = all
max_cron_threads = 0
log_level = info
