{
    "name": "EL MOKRIF Tendering & BOQ",
    "summary": "Versioned BOQs, rate analysis, tender leveling, and controlled awards",
    "version": "17.0.1.0.0",
    "category": "Construction",
    "author": "EL MOKRIF",
    "license": "LGPL-3",
    "depends": [
        "elmokrif_chantier_estimation",
        "elmokrif_documents_bridge",
        "elmokrif_purchase_quality",
        "account",
        "purchase",
        "sale_management",
        "stock",
    ],
    "data": [
        "security/tender_boq_groups.xml",
        "security/ir.model.access.csv",
        "security/tender_boq_rules.xml",
        "data/tender_boq_sequences.xml",
        "views/boq_views.xml",
        "views/tender_views.xml",
        "views/integration_views.xml",
        "wizard/boq_workflow_wizard_views.xml",
        "views/tender_boq_menus.xml",
    ],
    "installable": True,
    "application": True,
}
